server:
  port: 8081
spring:
  application:
    name: account-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/accounts
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
